version: "3"

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    image: bennysaa/imgrio:vue-0.1.0
    container_name: imgrio-vue
    ports:
      - 80:80
      - 443:443
    restart: always