version: "3"

services:
  react:
    build:
      context: ./imgrio-react
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    
  api:
    build:
      context: ./imgrio-api
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8443:443
    restart: always