version: "3"

services:
  react:
    image: bennysaa/imgrio:react-0.1.0
    ports:
      - 80:80
      - 443:443
    restart: always

  api:
    image: bennysaa/imgrio:api-0.1.0
    ports:
      - 8080:80
      - 8443:443
    restart: always