version: "3"

services:
  vue:
    build:
      context: ./imgrio-vue
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always

  api:
    build:
      context: ./imgrio-api
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8443:443
    restart: always
