version: "3"

services:
  imgrio-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bennysaa/imgrio:api-0.2.0
    container_name: imgrio-api
    ports:
      - 443:443
    restart: always